repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix, lf]
  - repo: local
    hooks:
      - id: tofu-fmt
        name: tofu format
        description: Format .tf files
        entry: tofu fmt
        language: system
        files: .tf$
